/* ============================================================
   SS DELPHINE — SHELL BEHAVIOUR
   Phase 0 output. Menu, active section, Read more.
   Section authors do not edit this file.

   One scroll listener for the whole page lives in statement.js.
   Active-section tracking uses IntersectionObserver, not scroll.
   ============================================================ */
(() => {
  'use strict';

  const root = document.documentElement;

  /* ---------- Mobile menu: full-screen navy panel ---------- */
  const nav = document.querySelector('#primary-navigation');
  const toggle = document.querySelector('.nav-toggle');
  const closeBtn = document.querySelector('.nav__close');

  const setMenu = (open) => {
    if (!nav || !toggle) return;
    nav.dataset.open = String(open);
    toggle.setAttribute('aria-expanded', String(open));
    root.style.overflow = open ? 'hidden' : '';
    if (open) {
      (nav.querySelector('.nav__link') || nav).focus?.();
    } else {
      toggle.focus();
    }
  };

  toggle?.addEventListener('click', () => setMenu(nav.dataset.open !== 'true'));
  closeBtn?.addEventListener('click', () => setMenu(false));

  // Anchor links close the panel so the destination is visible.
  nav?.querySelectorAll('.nav__link').forEach((a) => {
    a.addEventListener('click', () => setMenu(false));
  });

  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && nav?.dataset.open === 'true') setMenu(false);
  });

  /* ---------- Header ground once the hero is behind us ---------- */
  const header = document.querySelector('[data-site-header]');
  const hero = document.querySelector('.hero');
  if (header && hero && 'IntersectionObserver' in window) {
    new IntersectionObserver(
      ([entry]) => { header.dataset.scrolled = String(!entry.isIntersecting); },
      { rootMargin: '-70% 0px 0px 0px' }
    ).observe(hero);
  }

  /* ---------- Active section, hairline gold underline ---------- */
  const links = [...document.querySelectorAll('.nav__link')];
  const targets = links
    .map((l) => document.querySelector(l.getAttribute('href')))
    .filter(Boolean);

  if (targets.length && 'IntersectionObserver' in window) {
    const seen = new Map();
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((en) => seen.set(en.target.id, en.intersectionRatio));
        let bestId = null;
        let bestRatio = 0;
        seen.forEach((ratio, id) => {
          if (ratio > bestRatio) { bestRatio = ratio; bestId = id; }
        });
        links.forEach((l) => {
          const on = bestId !== null && l.getAttribute('href') === `#${bestId}`;
          if (on) l.setAttribute('aria-current', 'true');
          else l.removeAttribute('aria-current');
        });
      },
      { threshold: [0, 0.25, 0.5, 0.75, 1], rootMargin: '-20% 0px -35% 0px' }
    );
    targets.forEach((t) => observer.observe(t));
  }

  /* ---------- Read more: the four-sentence rule ----------
     Expands in place. Never moves the scroll position. */
  document.querySelectorAll('.readmore').forEach((block) => {
    const btn = block.querySelector('.readmore__toggle');
    const panel = block.querySelector('.readmore__panel');
    if (!btn || !panel) return;

    if (!panel.id) panel.id = `rm-${Math.random().toString(36).slice(2, 8)}`;
    btn.setAttribute('aria-controls', panel.id);
    btn.setAttribute('aria-expanded', 'false');
    block.dataset.open = 'false';
    panel.hidden = false;

    btn.addEventListener('click', () => {
      const open = block.dataset.open !== 'true';
      block.dataset.open = String(open);
      btn.setAttribute('aria-expanded', String(open));
      btn.textContent = open ? 'Read less' : 'Read more';
    });
  });
})();
